#!/usr/bin/env bash
# Answer to what type of network a computer in local is connected to:
echo "LAN"

# Answer to what type of network connects an office in one building to another office in a building a few streets away:
echo "LAN"

# Answer to what network is used when browsing www.google.com from a smartphone (not connected to WiFi):
echo "WAN"
