#!/usr/bin/env bash
# Answer to the correct statement for TCP:
echo "It is a protocol that is transferring data in a slow way but surely"

# Answer to the correct statement for UDP:
echo "It is a protocol that is transferring data in a fast way and might lose data along in the process"

# Answer to the correct statement for TCP worker:
echo "Have you received boxes x, y, z?"

# Answer to the correct statement for UDP worker:
echo "May I increase the rate at which I am sending you boxes?"
